export const habitData = [
  {
    id: "1LaUlBJ3t1sZQvaz51MZ",
    category: "sport",
    title: "Велисопед",
    type: "habit",
    complexity: 5,
    sphereId: "lrkqn7lv",
    valueType: "measures",
    habitsCategoryId: "lrkqn7lv",
    description: "",
    scheduleTime: ["18", "00"],
    isHidden: true,
    fields: [
      {
        orderIndex: 0,
        name: "Час",
        minToComplete: 20,
        unit: "хв",
        id: "lr0i6eo1",
      },
    ],
  },
  {
    id: "2Zo28XivTcfd1VS9LRim",
    title: "Медитація",
    habitsCategoryId: "NzVcHBavOeOI69awQ7GM",
    type: "habit",
    description: "",
    category: ["kpkOGBZvtn69YMc9lNTM", "O2mn5i61U1pr2YgKjZ2h"],
    valueType: "measures",
    complexity: 3,
    fields: [
      {
        id: "lr0i1kp2",
        name: "Час",
        minToComplete: 17,
        unit: "хв",
        orderIndex: 0,
      },
    ],
    scheduleTime: ["7", "00"],
    isHidden: false,
  },
  {
    id: "38WBGbHDeMQ4NEdGbECR",
    complexity: 5,
    habitsCategoryId: "lrnicx2i",
    category: "daily",
    type: "habit",
    sphereId: "lrkqn7lv",
    scheduleTime: ["6", "15"],
    valueType: "measures",
    fields: [
      {
        minToComplete: 84,
        id: "lr0i8mbs",
        orderIndex: 0,
        unit: "кг",
        name: "Вага",
      },
    ],
    description: "",
    isHidden: false,
    title: "Вага",
  },
  {
    id: "3YIPG6TCkQq3GwWoxsbG",
    title: "Зарядка (розминка)",
    scheduleTime: ["6", 20],
    habitCategory: "NzVcHBavOeOI69awQ7GM",
    valueType: "measures",
    sphereId: "lrkqn7lv",
    habitsCategoryId: "NzVcHBavOeOI69awQ7GM",
    isHidden: false,
    complexity: 3,
    description: "",
    fields: [
      {
        id: "lr0i161d",
        unit: "хв",
        name: "Час",
        minToComplete: 10,
        orderIndex: 0,
      },
    ],
    type: "habit",
    category: "morning",
  },
  {
    id: "8kyTLLC8zDmBchy7ihwz",
    valueType: "measures",
    type: "habit",
    category: "other",
    habitsCategoryId: "lrnicx2i",
    fields: [
      {
        orderIndex: 0,
        unit: "мл",
        id: "lr0i2x56",
        minToComplete: 2500,
        name: "Об'єм",
      },
    ],
    description: "",
    scheduleTime: "",
    complexity: 4,
    isHidden: false,
    sphereId: "",
    title: "Вода",
  },
  {
    id: "BoHeKDRQoWWOmYOHd8Fk",
    isHidden: false,
    description: "",
    type: "habit",
    category: "morning",
    fields: [
      {
        name: "Час",
        unit: "хв",
        minToComplete: 45,
        id: "lr0i1y48",
        orderIndex: 0,
      },
      {
        name: "Останній урок",
        minToComplete: 0,
        id: "lrgkr0uv",
        orderIndex: 1,
        unit: "№",
      },
    ],
    title: "Англійська мова (уроки)",
    scheduleTime: ["8", "00"],
    valueType: "measures",
    complexity: 6,
    habitsCategoryId: "NzVcHBavOeOI69awQ7GM",
  },
  {
    id: "EcwPJDP3kKvtwb83w89z",
    isHidden: true,
    scheduleTime: ["6", 15],
    fields: [
      {
        unit: "хв",
        minToComplete: 10,
        id: "lr0hxl8o",
        name: "Час",
        orderIndex: 0,
      },
    ],
    valueType: "measures",
    habitsCategoryId: "lrnicx2i",
    title: "Зарядка (силова)",
    description: "",
    type: "habit",
    complexity: 5,
    category: "morning",
  },
  {
    id: "HHV4XyKlN6clndlRJgqF",
    isHidden: false,
    title: "Басейн",
    fields: [
      {
        id: "lr0i2k4g",
        name: "Час",
        unit: "хв",
        orderIndex: 0,
        minToComplete: 50,
      },
    ],
    type: "habit",
    description: "",
    category: "sport",
    complexity: 2,
    habitsCategoryId: "lrnicx2i",
    scheduleTime: ["18", "00"],
    valueType: "measures",
  },
  {
    id: "HSpJI3qbJFJLsjhe3fiF",
    complexity: 1,
    valueType: "boolean",
    type: "habit",
    scheduleTime: ["9", "00"],
    title: "Офіс",
    category: "daily",
    habitsCategoryId: "lrnicx2i",
    description: "",
  },
  {
    id: "HxiAc1u6vs8B1Clqaf9o",
    valueType: "measures",
    type: "habit",
    isHidden: true,
    category: "sport",
    scheduleTime: ["18", "00"],
    fields: [
      {
        orderIndex: 0,
        minToComplete: 30,
        id: "lr0i2gd5",
        unit: "хв",
        name: "Час",
      },
    ],
    complexity: 7,
    description: "",
    title: "Спортзал",
    habitsCategoryId: "lrnicx2i",
  },
  {
    id: "I0JDjq9aPeVbnuRZJIcJ",
    habitsCategoryId: "NzVcHBavOeOI69awQ7GM",
    complexity: 6,
    description: "",
    valueType: "measures",
    fields: [
      {
        minToComplete: 10,
        orderIndex: 0,
        name: "Час",
        id: "lr0ie0dl",
        unit: "хв",
      },
    ],
    isHidden: true,
    title: "Зарядка (кардіо 30 днів)",
    scheduleTime: ["6", "45"],
    category: "sport",
    type: "habit",
  },
  {
    id: "M0wLJ2PElcpFkEY1txko",
    valueType: "measures",
    fields: [
      {
        minToComplete: 20,
        name: "Час",
        orderIndex: 0,
        unit: "хв",
        id: "lr0i2t80",
      },
    ],
    complexity: 5,
    category: "sport",
    habitsCategoryId: "lrnicx2i",
    title: "Баскетбол",
    scheduleTime: ["20", "00"],
    description: "",
    isHidden: false,
    type: "habit",
  },
  {
    id: "Mb0rvgCRk0GAz7ipiL3S",
    isHidden: false,
    category: "morning",
    sphereId: "",
    type: "habit",
    fields: [
      {
        name: "Час",
        orderIndex: 0,
        minToComplete: 10,
        unit: "хв",
        id: "lrq7fgrb",
      },
    ],
    title: "Вигуляти Інді",
    habitsCategoryId: "NzVcHBavOeOI69awQ7GM",
    complexity: 3,
    valueType: "boolean",
    scheduleTime: ["6", "20"],
    description: "",
  },
  {
    id: "O0V3t6xqZBk5Wfo1LuTn",
    category: "daily",
    expiredDate: "Invalid Date",
    valueType: "measures",
    isHidden: true,
    scheduleTime: "",
    complexity: 5,
    description: "(з годиника)",
    habitsCategoryId: "lrnicx2i",
    fields: [
      {
        name: "Час",
        unit: "годин",
        id: "lr0hwuiz",
        minToComplete: 6,
        orderIndex: 0,
      },
    ],
    createAt: "14/08/2023",
    type: "habit",
    title: "Час сну",
    startFrom: "01/07/2023",
  },
  {
    id: "RWGB0nZJW7wqQdqPcESf",
    title: "10 Цілей",
    scheduleTime: ["8", "10"],
    habitsCategoryId: "NzVcHBavOeOI69awQ7GM",
    complexity: 1,
    description: "",
    category: "morning",
    type: "habit",
    valueType: "boolean",
  },
  {
    id: "TUhqO1wNgAkUJCGU8sHh",
    description: "",
    title: "Фортепіано",
    type: "habit",
    valueType: "measures",
    isHidden: true,
    complexity: 6,
    fields: [
      {
        unit: "хв",
        minToComplete: 30,
        id: "lr0i2b9q",
        name: "Час",
        orderIndex: 0,
      },
    ],
    scheduleTime: ["17", "00"],
    category: "daily",
    habitsCategoryId: "lrnicx2i",
  },
  {
    id: "V81KRuORKBaiLCWPJPym",
    title: "Лампа",
    complexity: 2,
    fields: [
      {
        unit: "хв",
        minToComplete: 90,
        name: "Час",
        orderIndex: 0,
        id: "lr0i1elj",
      },
    ],
    isHidden: false,
    description: "",
    type: "habit",
    category: "morning",
    habitsCategoryId: "lrnidju5",
    valueType: "measures",
    scheduleTime: ["6", "30"],
  },
  {
    id: "aetszBHGObtOXNSOoqe3",
    title: "Контрасний душ",
    scheduleTime: ["6", "00"],
    description: "",
    habitsCategoryId: "NzVcHBavOeOI69awQ7GM",
    valueType: "boolean",
    category: "morning",
    isHidden: true,
    complexity: 3,
    type: "habit",
  },
  {
    id: "ayadlRqX5UcOmDWqheQa",
    title: "Біг",
    type: "habit",
    complexity: 7,
    habitsCategoryId: "lrnidju5",
    scheduleTime: ["6", "15"],
    category: "sport",
    fields: [
      {
        orderIndex: 1,
        name: "Відстань",
        minToComplete: 6,
        unit: "км",
        id: "lr0h1md1",
      },
      {
        orderIndex: 0,
        unit: "хв",
        name: "Час",
        minToComplete: 45,
        id: "lr0h1md0",
      },
      {
        orderIndex: 2,
        id: "lr0h1md2",
        name: "Калорії",
        unit: "Ккал",
        minToComplete: 500,
      },
    ],
    description: "",
    valueType: "measures",
    isHidden: false,
  },
  {
    id: "gwF4uCpzMfj819r1fgXW",
  },
  {
    id: "hfoQQWtbCENzUhptPUU8",
    type: "habit",
    isHidden: false,
    valueType: "boolean",
    category: "daily",
    title: "Догляд за шкірою",
    scheduleTime: ["20", "00"],
    complexity: 2,
    description: "",
    habitsCategoryId: "fhfa87yfejFHsUEHinO3",
  },
  {
    id: "j3QmpEQqWK25rQptgPdp",
  },
  {
    id: "le03haKYguF9qIg07FmM",
    description: "",
    habitsCategoryId: "lrnicx2i",
    type: "habit",
    startFrom: "01/07/2023",
    complexity: 1,
    createAt: "29/07/2023",
    title: "Лікарняне",
    expiredDate: "Invalid Date",
    category: "daily",
    valueType: "boolean",
  },
  {
    id: "n4RqKXRNAjn6sBh4ZBTn",
    isHidden: false,
    title: "Комп. гра",
    description: "",
    category: "daily",
    valueType: "measures",
    type: "habit",
    complexity: 1,
    habitsCategoryId: "lrnicx2i",
    scheduleTime: ["19", "00"],
    fields: [
      {
        minToComplete: 60,
        orderIndex: 0,
        name: "Час",
        id: "lr0i2smt",
        unit: "хв",
      },
    ],
  },
  {
    id: "nicBHKsGlhBctqMUN5UO",
    category: "daily",
    complexity: 5,
    scheduleTime: ["8", "30"],
    description: "",
    type: "habit",
    title: "Робота",
    valueType: "boolean",
    habitsCategoryId: "lrnidju5",
  },
  {
    id: "ojbEECaENfxXZOFCx8zn",
    category: "daily",
    habitsCategoryId: "fhfa87yfejFHsUEHinO3",
    valueType: "boolean",
    complexity: 3,
    title: "3 секунди відео",
    description: "",
    startFrom: "01/07/2023",
    expiredDate: "Invalid Date",
    createAt: "29/07/2023",
    type: "habit",
  },
  {
    id: "qKq1o9kP6XfeiUqgho3N",
    isHidden: false,
    type: "habit",
    description: "",
    category: "daily",
    valueType: "measures",
    scheduleTime: ["21", "30"],
    title: "Аплікатор",
    habitsCategoryId: "fhfa87yfejFHsUEHinO3",
    fields: [
      {
        id: "lr0i2u7p",
        minToComplete: 10,
        unit: "хв",
        name: "Час",
        orderIndex: 0,
      },
    ],
    complexity: 2,
  },
  {
    id: "qPeQVUpw8aqRXz0kcKGS",
    complexity: 5,
    fields: [
      {
        name: "Час",
        minToComplete: 120,
        unit: "хв",
        id: "lr0i26vk",
        orderIndex: 0,
      },
    ],
    scheduleTime: ["11", "00"],
    type: "habit",
    valueType: "measures",
    category: "daily",
    title: "Програмування",
    description: "Навчання",
    habitsCategoryId: "lrnidju5",
    isHidden: false,
  },
  {
    id: "se0AjTXCwqRVW9uRaIKu",
    type: "habit",
    valueType: "measures",
    fields: [
      {
        id: "lr0i1smo",
        minToComplete: 9,
        unit: "хв",
        orderIndex: 0,
        name: "Час",
      },
    ],
    complexity: 2,
    title: "Вакуум",
    description: "",
    isHidden: false,
    habitsCategoryId: "NzVcHBavOeOI69awQ7GM",
    category: "morning",
    scheduleTime: ["7", "25"],
  },
  {
    id: "uxrC7xQocaTqRdB4B1lA",
    title: "Лук",
    type: "habit",
    valueType: "measures",
    category: "sport",
    isHidden: true,
    scheduleTime: ["18", "00"],
    description: "",
    habitsCategoryId: "lrnicx2i",
    complexity: 7,
  },
];
